/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as Char123LocaleChar125RouteRouteImport } from "./routes/{-$locale}/route"
import { Route as Char123LocaleChar125MainRouteRouteImport } from "./routes/{-$locale}/_main/route"
import { Route as Char123LocaleChar125MainIndexRouteImport } from "./routes/{-$locale}/_main/index"
import { Route as Char123LocaleChar125MainSettingsRouteImport } from "./routes/{-$locale}/_main/settings"
import { Route as Char123LocaleChar125MainSettingsPreferencesRouteImport } from "./routes/{-$locale}/_main/settings.preferences"
import { Route as Char123LocaleChar125MainQuizNewRouteImport } from "./routes/{-$locale}/_main/quiz.new"
import { Route as Char123LocaleChar125MainQuizQuizIdRouteImport } from "./routes/{-$locale}/_main/quiz.$quizId"
import { Route as Char123LocaleChar125MainQuizNewManualRouteImport } from "./routes/{-$locale}/_main/quiz.new.manual"
import { Route as Char123LocaleChar125MainQuizNewAiRouteImport } from "./routes/{-$locale}/_main/quiz.new.ai"
import { Route as Char123LocaleChar125MainQuizQuizIdEditRouteImport } from "./routes/{-$locale}/_main/quiz.$quizId.edit"
import { Route as Char123LocaleChar125MainQuizNewManualQuestionIdRouteImport } from "./routes/{-$locale}/_main/quiz.new.manual.$questionId"
import { Route as Char123LocaleChar125MainQuizQuizIdEditAiRouteImport } from "./routes/{-$locale}/_main/quiz.$quizId.edit.ai"
import { Route as Char123LocaleChar125MainQuizQuizIdEditQuestionIdRouteImport } from "./routes/{-$locale}/_main/quiz.$quizId.edit.$questionId"

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: "/{-$locale}",
    path: "/{-$locale}",
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125MainRouteRoute =
  Char123LocaleChar125MainRouteRouteImport.update({
    id: "/_main",
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MainIndexRoute =
  Char123LocaleChar125MainIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125MainSettingsRoute =
  Char123LocaleChar125MainSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125MainSettingsPreferencesRoute =
  Char123LocaleChar125MainSettingsPreferencesRouteImport.update({
    id: "/preferences",
    path: "/preferences",
    getParentRoute: () => Char123LocaleChar125MainSettingsRoute,
  } as any)
const Char123LocaleChar125MainQuizNewRoute =
  Char123LocaleChar125MainQuizNewRouteImport.update({
    id: "/quiz/new",
    path: "/quiz/new",
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125MainQuizQuizIdRoute =
  Char123LocaleChar125MainQuizQuizIdRouteImport.update({
    id: "/quiz/$quizId",
    path: "/quiz/$quizId",
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125MainQuizNewManualRoute =
  Char123LocaleChar125MainQuizNewManualRouteImport.update({
    id: "/manual",
    path: "/manual",
    getParentRoute: () => Char123LocaleChar125MainQuizNewRoute,
  } as any)
const Char123LocaleChar125MainQuizNewAiRoute =
  Char123LocaleChar125MainQuizNewAiRouteImport.update({
    id: "/ai",
    path: "/ai",
    getParentRoute: () => Char123LocaleChar125MainQuizNewRoute,
  } as any)
const Char123LocaleChar125MainQuizQuizIdEditRoute =
  Char123LocaleChar125MainQuizQuizIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => Char123LocaleChar125MainQuizQuizIdRoute,
  } as any)
const Char123LocaleChar125MainQuizNewManualQuestionIdRoute =
  Char123LocaleChar125MainQuizNewManualQuestionIdRouteImport.update({
    id: "/$questionId",
    path: "/$questionId",
    getParentRoute: () => Char123LocaleChar125MainQuizNewManualRoute,
  } as any)
const Char123LocaleChar125MainQuizQuizIdEditAiRoute =
  Char123LocaleChar125MainQuizQuizIdEditAiRouteImport.update({
    id: "/ai",
    path: "/ai",
    getParentRoute: () => Char123LocaleChar125MainQuizQuizIdEditRoute,
  } as any)
const Char123LocaleChar125MainQuizQuizIdEditQuestionIdRoute =
  Char123LocaleChar125MainQuizQuizIdEditQuestionIdRouteImport.update({
    id: "/$questionId",
    path: "/$questionId",
    getParentRoute: () => Char123LocaleChar125MainQuizQuizIdEditRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/{-$locale}": typeof Char123LocaleChar125MainRouteRouteWithChildren
  "/{-$locale}/settings": typeof Char123LocaleChar125MainSettingsRouteWithChildren
  "/{-$locale}/": typeof Char123LocaleChar125MainIndexRoute
  "/{-$locale}/quiz/$quizId": typeof Char123LocaleChar125MainQuizQuizIdRouteWithChildren
  "/{-$locale}/quiz/new": typeof Char123LocaleChar125MainQuizNewRouteWithChildren
  "/{-$locale}/settings/preferences": typeof Char123LocaleChar125MainSettingsPreferencesRoute
  "/{-$locale}/quiz/$quizId/edit": typeof Char123LocaleChar125MainQuizQuizIdEditRouteWithChildren
  "/{-$locale}/quiz/new/ai": typeof Char123LocaleChar125MainQuizNewAiRoute
  "/{-$locale}/quiz/new/manual": typeof Char123LocaleChar125MainQuizNewManualRouteWithChildren
  "/{-$locale}/quiz/$quizId/edit/$questionId": typeof Char123LocaleChar125MainQuizQuizIdEditQuestionIdRoute
  "/{-$locale}/quiz/$quizId/edit/ai": typeof Char123LocaleChar125MainQuizQuizIdEditAiRoute
  "/{-$locale}/quiz/new/manual/$questionId": typeof Char123LocaleChar125MainQuizNewManualQuestionIdRoute
}
export interface FileRoutesByTo {
  "/{-$locale}": typeof Char123LocaleChar125MainIndexRoute
  "/{-$locale}/settings": typeof Char123LocaleChar125MainSettingsRouteWithChildren
  "/{-$locale}/quiz/$quizId": typeof Char123LocaleChar125MainQuizQuizIdRouteWithChildren
  "/{-$locale}/quiz/new": typeof Char123LocaleChar125MainQuizNewRouteWithChildren
  "/{-$locale}/settings/preferences": typeof Char123LocaleChar125MainSettingsPreferencesRoute
  "/{-$locale}/quiz/$quizId/edit": typeof Char123LocaleChar125MainQuizQuizIdEditRouteWithChildren
  "/{-$locale}/quiz/new/ai": typeof Char123LocaleChar125MainQuizNewAiRoute
  "/{-$locale}/quiz/new/manual": typeof Char123LocaleChar125MainQuizNewManualRouteWithChildren
  "/{-$locale}/quiz/$quizId/edit/$questionId": typeof Char123LocaleChar125MainQuizQuizIdEditQuestionIdRoute
  "/{-$locale}/quiz/$quizId/edit/ai": typeof Char123LocaleChar125MainQuizQuizIdEditAiRoute
  "/{-$locale}/quiz/new/manual/$questionId": typeof Char123LocaleChar125MainQuizNewManualQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/{-$locale}": typeof Char123LocaleChar125RouteRouteWithChildren
  "/{-$locale}/_main": typeof Char123LocaleChar125MainRouteRouteWithChildren
  "/{-$locale}/_main/settings": typeof Char123LocaleChar125MainSettingsRouteWithChildren
  "/{-$locale}/_main/": typeof Char123LocaleChar125MainIndexRoute
  "/{-$locale}/_main/quiz/$quizId": typeof Char123LocaleChar125MainQuizQuizIdRouteWithChildren
  "/{-$locale}/_main/quiz/new": typeof Char123LocaleChar125MainQuizNewRouteWithChildren
  "/{-$locale}/_main/settings/preferences": typeof Char123LocaleChar125MainSettingsPreferencesRoute
  "/{-$locale}/_main/quiz/$quizId/edit": typeof Char123LocaleChar125MainQuizQuizIdEditRouteWithChildren
  "/{-$locale}/_main/quiz/new/ai": typeof Char123LocaleChar125MainQuizNewAiRoute
  "/{-$locale}/_main/quiz/new/manual": typeof Char123LocaleChar125MainQuizNewManualRouteWithChildren
  "/{-$locale}/_main/quiz/$quizId/edit/$questionId": typeof Char123LocaleChar125MainQuizQuizIdEditQuestionIdRoute
  "/{-$locale}/_main/quiz/$quizId/edit/ai": typeof Char123LocaleChar125MainQuizQuizIdEditAiRoute
  "/{-$locale}/_main/quiz/new/manual/$questionId": typeof Char123LocaleChar125MainQuizNewManualQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/{-$locale}"
    | "/{-$locale}/settings"
    | "/{-$locale}/"
    | "/{-$locale}/quiz/$quizId"
    | "/{-$locale}/quiz/new"
    | "/{-$locale}/settings/preferences"
    | "/{-$locale}/quiz/$quizId/edit"
    | "/{-$locale}/quiz/new/ai"
    | "/{-$locale}/quiz/new/manual"
    | "/{-$locale}/quiz/$quizId/edit/$questionId"
    | "/{-$locale}/quiz/$quizId/edit/ai"
    | "/{-$locale}/quiz/new/manual/$questionId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/{-$locale}"
    | "/{-$locale}/settings"
    | "/{-$locale}/quiz/$quizId"
    | "/{-$locale}/quiz/new"
    | "/{-$locale}/settings/preferences"
    | "/{-$locale}/quiz/$quizId/edit"
    | "/{-$locale}/quiz/new/ai"
    | "/{-$locale}/quiz/new/manual"
    | "/{-$locale}/quiz/$quizId/edit/$questionId"
    | "/{-$locale}/quiz/$quizId/edit/ai"
    | "/{-$locale}/quiz/new/manual/$questionId"
  id:
    | "__root__"
    | "/{-$locale}"
    | "/{-$locale}/_main"
    | "/{-$locale}/_main/settings"
    | "/{-$locale}/_main/"
    | "/{-$locale}/_main/quiz/$quizId"
    | "/{-$locale}/_main/quiz/new"
    | "/{-$locale}/_main/settings/preferences"
    | "/{-$locale}/_main/quiz/$quizId/edit"
    | "/{-$locale}/_main/quiz/new/ai"
    | "/{-$locale}/_main/quiz/new/manual"
    | "/{-$locale}/_main/quiz/$quizId/edit/$questionId"
    | "/{-$locale}/_main/quiz/$quizId/edit/ai"
    | "/{-$locale}/_main/quiz/new/manual/$questionId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/{-$locale}": {
      id: "/{-$locale}"
      path: "/{-$locale}"
      fullPath: "/{-$locale}"
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/{-$locale}/_main": {
      id: "/{-$locale}/_main"
      path: ""
      fullPath: "/{-$locale}"
      preLoaderRoute: typeof Char123LocaleChar125MainRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    "/{-$locale}/_main/": {
      id: "/{-$locale}/_main/"
      path: "/"
      fullPath: "/{-$locale}/"
      preLoaderRoute: typeof Char123LocaleChar125MainIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    "/{-$locale}/_main/settings": {
      id: "/{-$locale}/_main/settings"
      path: "/settings"
      fullPath: "/{-$locale}/settings"
      preLoaderRoute: typeof Char123LocaleChar125MainSettingsRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    "/{-$locale}/_main/settings/preferences": {
      id: "/{-$locale}/_main/settings/preferences"
      path: "/preferences"
      fullPath: "/{-$locale}/settings/preferences"
      preLoaderRoute: typeof Char123LocaleChar125MainSettingsPreferencesRouteImport
      parentRoute: typeof Char123LocaleChar125MainSettingsRoute
    }
    "/{-$locale}/_main/quiz/new": {
      id: "/{-$locale}/_main/quiz/new"
      path: "/quiz/new"
      fullPath: "/{-$locale}/quiz/new"
      preLoaderRoute: typeof Char123LocaleChar125MainQuizNewRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    "/{-$locale}/_main/quiz/$quizId": {
      id: "/{-$locale}/_main/quiz/$quizId"
      path: "/quiz/$quizId"
      fullPath: "/{-$locale}/quiz/$quizId"
      preLoaderRoute: typeof Char123LocaleChar125MainQuizQuizIdRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    "/{-$locale}/_main/quiz/new/manual": {
      id: "/{-$locale}/_main/quiz/new/manual"
      path: "/manual"
      fullPath: "/{-$locale}/quiz/new/manual"
      preLoaderRoute: typeof Char123LocaleChar125MainQuizNewManualRouteImport
      parentRoute: typeof Char123LocaleChar125MainQuizNewRoute
    }
    "/{-$locale}/_main/quiz/new/ai": {
      id: "/{-$locale}/_main/quiz/new/ai"
      path: "/ai"
      fullPath: "/{-$locale}/quiz/new/ai"
      preLoaderRoute: typeof Char123LocaleChar125MainQuizNewAiRouteImport
      parentRoute: typeof Char123LocaleChar125MainQuizNewRoute
    }
    "/{-$locale}/_main/quiz/$quizId/edit": {
      id: "/{-$locale}/_main/quiz/$quizId/edit"
      path: "/edit"
      fullPath: "/{-$locale}/quiz/$quizId/edit"
      preLoaderRoute: typeof Char123LocaleChar125MainQuizQuizIdEditRouteImport
      parentRoute: typeof Char123LocaleChar125MainQuizQuizIdRoute
    }
    "/{-$locale}/_main/quiz/new/manual/$questionId": {
      id: "/{-$locale}/_main/quiz/new/manual/$questionId"
      path: "/$questionId"
      fullPath: "/{-$locale}/quiz/new/manual/$questionId"
      preLoaderRoute: typeof Char123LocaleChar125MainQuizNewManualQuestionIdRouteImport
      parentRoute: typeof Char123LocaleChar125MainQuizNewManualRoute
    }
    "/{-$locale}/_main/quiz/$quizId/edit/ai": {
      id: "/{-$locale}/_main/quiz/$quizId/edit/ai"
      path: "/ai"
      fullPath: "/{-$locale}/quiz/$quizId/edit/ai"
      preLoaderRoute: typeof Char123LocaleChar125MainQuizQuizIdEditAiRouteImport
      parentRoute: typeof Char123LocaleChar125MainQuizQuizIdEditRoute
    }
    "/{-$locale}/_main/quiz/$quizId/edit/$questionId": {
      id: "/{-$locale}/_main/quiz/$quizId/edit/$questionId"
      path: "/$questionId"
      fullPath: "/{-$locale}/quiz/$quizId/edit/$questionId"
      preLoaderRoute: typeof Char123LocaleChar125MainQuizQuizIdEditQuestionIdRouteImport
      parentRoute: typeof Char123LocaleChar125MainQuizQuizIdEditRoute
    }
  }
}

interface Char123LocaleChar125MainSettingsRouteChildren {
  Char123LocaleChar125MainSettingsPreferencesRoute: typeof Char123LocaleChar125MainSettingsPreferencesRoute
}

const Char123LocaleChar125MainSettingsRouteChildren: Char123LocaleChar125MainSettingsRouteChildren =
  {
    Char123LocaleChar125MainSettingsPreferencesRoute:
      Char123LocaleChar125MainSettingsPreferencesRoute,
  }

const Char123LocaleChar125MainSettingsRouteWithChildren =
  Char123LocaleChar125MainSettingsRoute._addFileChildren(
    Char123LocaleChar125MainSettingsRouteChildren,
  )

interface Char123LocaleChar125MainQuizQuizIdEditRouteChildren {
  Char123LocaleChar125MainQuizQuizIdEditQuestionIdRoute: typeof Char123LocaleChar125MainQuizQuizIdEditQuestionIdRoute
  Char123LocaleChar125MainQuizQuizIdEditAiRoute: typeof Char123LocaleChar125MainQuizQuizIdEditAiRoute
}

const Char123LocaleChar125MainQuizQuizIdEditRouteChildren: Char123LocaleChar125MainQuizQuizIdEditRouteChildren =
  {
    Char123LocaleChar125MainQuizQuizIdEditQuestionIdRoute:
      Char123LocaleChar125MainQuizQuizIdEditQuestionIdRoute,
    Char123LocaleChar125MainQuizQuizIdEditAiRoute:
      Char123LocaleChar125MainQuizQuizIdEditAiRoute,
  }

const Char123LocaleChar125MainQuizQuizIdEditRouteWithChildren =
  Char123LocaleChar125MainQuizQuizIdEditRoute._addFileChildren(
    Char123LocaleChar125MainQuizQuizIdEditRouteChildren,
  )

interface Char123LocaleChar125MainQuizQuizIdRouteChildren {
  Char123LocaleChar125MainQuizQuizIdEditRoute: typeof Char123LocaleChar125MainQuizQuizIdEditRouteWithChildren
}

const Char123LocaleChar125MainQuizQuizIdRouteChildren: Char123LocaleChar125MainQuizQuizIdRouteChildren =
  {
    Char123LocaleChar125MainQuizQuizIdEditRoute:
      Char123LocaleChar125MainQuizQuizIdEditRouteWithChildren,
  }

const Char123LocaleChar125MainQuizQuizIdRouteWithChildren =
  Char123LocaleChar125MainQuizQuizIdRoute._addFileChildren(
    Char123LocaleChar125MainQuizQuizIdRouteChildren,
  )

interface Char123LocaleChar125MainQuizNewManualRouteChildren {
  Char123LocaleChar125MainQuizNewManualQuestionIdRoute: typeof Char123LocaleChar125MainQuizNewManualQuestionIdRoute
}

const Char123LocaleChar125MainQuizNewManualRouteChildren: Char123LocaleChar125MainQuizNewManualRouteChildren =
  {
    Char123LocaleChar125MainQuizNewManualQuestionIdRoute:
      Char123LocaleChar125MainQuizNewManualQuestionIdRoute,
  }

const Char123LocaleChar125MainQuizNewManualRouteWithChildren =
  Char123LocaleChar125MainQuizNewManualRoute._addFileChildren(
    Char123LocaleChar125MainQuizNewManualRouteChildren,
  )

interface Char123LocaleChar125MainQuizNewRouteChildren {
  Char123LocaleChar125MainQuizNewAiRoute: typeof Char123LocaleChar125MainQuizNewAiRoute
  Char123LocaleChar125MainQuizNewManualRoute: typeof Char123LocaleChar125MainQuizNewManualRouteWithChildren
}

const Char123LocaleChar125MainQuizNewRouteChildren: Char123LocaleChar125MainQuizNewRouteChildren =
  {
    Char123LocaleChar125MainQuizNewAiRoute:
      Char123LocaleChar125MainQuizNewAiRoute,
    Char123LocaleChar125MainQuizNewManualRoute:
      Char123LocaleChar125MainQuizNewManualRouteWithChildren,
  }

const Char123LocaleChar125MainQuizNewRouteWithChildren =
  Char123LocaleChar125MainQuizNewRoute._addFileChildren(
    Char123LocaleChar125MainQuizNewRouteChildren,
  )

interface Char123LocaleChar125MainRouteRouteChildren {
  Char123LocaleChar125MainSettingsRoute: typeof Char123LocaleChar125MainSettingsRouteWithChildren
  Char123LocaleChar125MainIndexRoute: typeof Char123LocaleChar125MainIndexRoute
  Char123LocaleChar125MainQuizQuizIdRoute: typeof Char123LocaleChar125MainQuizQuizIdRouteWithChildren
  Char123LocaleChar125MainQuizNewRoute: typeof Char123LocaleChar125MainQuizNewRouteWithChildren
}

const Char123LocaleChar125MainRouteRouteChildren: Char123LocaleChar125MainRouteRouteChildren =
  {
    Char123LocaleChar125MainSettingsRoute:
      Char123LocaleChar125MainSettingsRouteWithChildren,
    Char123LocaleChar125MainIndexRoute: Char123LocaleChar125MainIndexRoute,
    Char123LocaleChar125MainQuizQuizIdRoute:
      Char123LocaleChar125MainQuizQuizIdRouteWithChildren,
    Char123LocaleChar125MainQuizNewRoute:
      Char123LocaleChar125MainQuizNewRouteWithChildren,
  }

const Char123LocaleChar125MainRouteRouteWithChildren =
  Char123LocaleChar125MainRouteRoute._addFileChildren(
    Char123LocaleChar125MainRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125MainRouteRoute: typeof Char123LocaleChar125MainRouteRouteWithChildren
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125MainRouteRoute:
      Char123LocaleChar125MainRouteRouteWithChildren,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
