/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as Char123LocaleChar125RouteRouteImport } from "./routes/{-$locale}/route"
import { Route as Char123LocaleChar125MainRouteRouteImport } from "./routes/{-$locale}/_main/route"
import { Route as Char123LocaleChar125MainIndexRouteImport } from "./routes/{-$locale}/_main/index"
import { Route as Char123LocaleChar125MainSettingsRouteImport } from "./routes/{-$locale}/_main/settings"
import { Route as Char123LocaleChar125MainSettingsPreferencesRouteImport } from "./routes/{-$locale}/_main/settings.preferences"
import { Route as Char123LocaleChar125MainQuizNewRouteImport } from "./routes/{-$locale}/_main/quiz.new"
import { Route as Char123LocaleChar125MainQuizQuizIdRouteImport } from "./routes/{-$locale}/_main/quiz.$quizId"

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: "/{-$locale}",
    path: "/{-$locale}",
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125MainRouteRoute =
  Char123LocaleChar125MainRouteRouteImport.update({
    id: "/_main",
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MainIndexRoute =
  Char123LocaleChar125MainIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125MainSettingsRoute =
  Char123LocaleChar125MainSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125MainSettingsPreferencesRoute =
  Char123LocaleChar125MainSettingsPreferencesRouteImport.update({
    id: "/preferences",
    path: "/preferences",
    getParentRoute: () => Char123LocaleChar125MainSettingsRoute,
  } as any)
const Char123LocaleChar125MainQuizNewRoute =
  Char123LocaleChar125MainQuizNewRouteImport.update({
    id: "/quiz/new",
    path: "/quiz/new",
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125MainQuizQuizIdRoute =
  Char123LocaleChar125MainQuizQuizIdRouteImport.update({
    id: "/quiz/$quizId",
    path: "/quiz/$quizId",
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/{-$locale}": typeof Char123LocaleChar125MainRouteRouteWithChildren
  "/{-$locale}/settings": typeof Char123LocaleChar125MainSettingsRouteWithChildren
  "/{-$locale}/": typeof Char123LocaleChar125MainIndexRoute
  "/{-$locale}/quiz/$quizId": typeof Char123LocaleChar125MainQuizQuizIdRoute
  "/{-$locale}/quiz/new": typeof Char123LocaleChar125MainQuizNewRoute
  "/{-$locale}/settings/preferences": typeof Char123LocaleChar125MainSettingsPreferencesRoute
}
export interface FileRoutesByTo {
  "/{-$locale}": typeof Char123LocaleChar125MainIndexRoute
  "/{-$locale}/settings": typeof Char123LocaleChar125MainSettingsRouteWithChildren
  "/{-$locale}/quiz/$quizId": typeof Char123LocaleChar125MainQuizQuizIdRoute
  "/{-$locale}/quiz/new": typeof Char123LocaleChar125MainQuizNewRoute
  "/{-$locale}/settings/preferences": typeof Char123LocaleChar125MainSettingsPreferencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/{-$locale}": typeof Char123LocaleChar125RouteRouteWithChildren
  "/{-$locale}/_main": typeof Char123LocaleChar125MainRouteRouteWithChildren
  "/{-$locale}/_main/settings": typeof Char123LocaleChar125MainSettingsRouteWithChildren
  "/{-$locale}/_main/": typeof Char123LocaleChar125MainIndexRoute
  "/{-$locale}/_main/quiz/$quizId": typeof Char123LocaleChar125MainQuizQuizIdRoute
  "/{-$locale}/_main/quiz/new": typeof Char123LocaleChar125MainQuizNewRoute
  "/{-$locale}/_main/settings/preferences": typeof Char123LocaleChar125MainSettingsPreferencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/{-$locale}"
    | "/{-$locale}/settings"
    | "/{-$locale}/"
    | "/{-$locale}/quiz/$quizId"
    | "/{-$locale}/quiz/new"
    | "/{-$locale}/settings/preferences"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/{-$locale}"
    | "/{-$locale}/settings"
    | "/{-$locale}/quiz/$quizId"
    | "/{-$locale}/quiz/new"
    | "/{-$locale}/settings/preferences"
  id:
    | "__root__"
    | "/{-$locale}"
    | "/{-$locale}/_main"
    | "/{-$locale}/_main/settings"
    | "/{-$locale}/_main/"
    | "/{-$locale}/_main/quiz/$quizId"
    | "/{-$locale}/_main/quiz/new"
    | "/{-$locale}/_main/settings/preferences"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/{-$locale}": {
      id: "/{-$locale}"
      path: "/{-$locale}"
      fullPath: "/{-$locale}"
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/{-$locale}/_main": {
      id: "/{-$locale}/_main"
      path: ""
      fullPath: "/{-$locale}"
      preLoaderRoute: typeof Char123LocaleChar125MainRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    "/{-$locale}/_main/": {
      id: "/{-$locale}/_main/"
      path: "/"
      fullPath: "/{-$locale}/"
      preLoaderRoute: typeof Char123LocaleChar125MainIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    "/{-$locale}/_main/settings": {
      id: "/{-$locale}/_main/settings"
      path: "/settings"
      fullPath: "/{-$locale}/settings"
      preLoaderRoute: typeof Char123LocaleChar125MainSettingsRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    "/{-$locale}/_main/settings/preferences": {
      id: "/{-$locale}/_main/settings/preferences"
      path: "/preferences"
      fullPath: "/{-$locale}/settings/preferences"
      preLoaderRoute: typeof Char123LocaleChar125MainSettingsPreferencesRouteImport
      parentRoute: typeof Char123LocaleChar125MainSettingsRoute
    }
    "/{-$locale}/_main/quiz/new": {
      id: "/{-$locale}/_main/quiz/new"
      path: "/quiz/new"
      fullPath: "/{-$locale}/quiz/new"
      preLoaderRoute: typeof Char123LocaleChar125MainQuizNewRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    "/{-$locale}/_main/quiz/$quizId": {
      id: "/{-$locale}/_main/quiz/$quizId"
      path: "/quiz/$quizId"
      fullPath: "/{-$locale}/quiz/$quizId"
      preLoaderRoute: typeof Char123LocaleChar125MainQuizQuizIdRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
  }
}

interface Char123LocaleChar125MainSettingsRouteChildren {
  Char123LocaleChar125MainSettingsPreferencesRoute: typeof Char123LocaleChar125MainSettingsPreferencesRoute
}

const Char123LocaleChar125MainSettingsRouteChildren: Char123LocaleChar125MainSettingsRouteChildren =
  {
    Char123LocaleChar125MainSettingsPreferencesRoute:
      Char123LocaleChar125MainSettingsPreferencesRoute,
  }

const Char123LocaleChar125MainSettingsRouteWithChildren =
  Char123LocaleChar125MainSettingsRoute._addFileChildren(
    Char123LocaleChar125MainSettingsRouteChildren,
  )

interface Char123LocaleChar125MainRouteRouteChildren {
  Char123LocaleChar125MainSettingsRoute: typeof Char123LocaleChar125MainSettingsRouteWithChildren
  Char123LocaleChar125MainIndexRoute: typeof Char123LocaleChar125MainIndexRoute
  Char123LocaleChar125MainQuizQuizIdRoute: typeof Char123LocaleChar125MainQuizQuizIdRoute
  Char123LocaleChar125MainQuizNewRoute: typeof Char123LocaleChar125MainQuizNewRoute
}

const Char123LocaleChar125MainRouteRouteChildren: Char123LocaleChar125MainRouteRouteChildren =
  {
    Char123LocaleChar125MainSettingsRoute:
      Char123LocaleChar125MainSettingsRouteWithChildren,
    Char123LocaleChar125MainIndexRoute: Char123LocaleChar125MainIndexRoute,
    Char123LocaleChar125MainQuizQuizIdRoute:
      Char123LocaleChar125MainQuizQuizIdRoute,
    Char123LocaleChar125MainQuizNewRoute: Char123LocaleChar125MainQuizNewRoute,
  }

const Char123LocaleChar125MainRouteRouteWithChildren =
  Char123LocaleChar125MainRouteRoute._addFileChildren(
    Char123LocaleChar125MainRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125MainRouteRoute: typeof Char123LocaleChar125MainRouteRouteWithChildren
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125MainRouteRoute:
      Char123LocaleChar125MainRouteRouteWithChildren,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
